// Відео я знайшов в інтернеті, просто для тесту, вони можуть в масиві повторюватись
// Відео я взяв звідси https://gist.github.com/SeunghoonBaek/f35e0fd3db80bf55c2707cae5d0f7184

export const initialCourses = [
  {
    id: 0,
    title: 'Title 0',
    description: 'Description 0',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    price: 10,
    currency: '$',
  },
  {
    id: 1,
    title: 'Title 1',
    description: 'Very Very Long Detailed Description about the course to show that long descriptions are possible 1',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    price: 50,
    currency: '$',
  },
  {
    id: 2,
    title: 'Very Long Course Title as Example 2',
    description: 'Description 2',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    price: 6,
    currency: '$',
  },
  {
    id: 3,
    title: 'Title 3',
    description: 'Description 3',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    price: 100,
    currency: '$',
  },
  {
    id: 4,
    title: 'Title 4',
    description: 'Description 4',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    price: 55,
    currency: '$',
  },
  {
    id: 5,
    title: 'Title 5',
    description: 'Description 5',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    price: 49,
    currency: '$',
  },
  {
    id: 6,
    title: 'Title 6',
    description: 'Description 6',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    price: 99,
    currency: '$',
  },
  {
    id: 7,
    title: 'Title 7',
    description: 'Description 7',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    price: 1,
    currency: '$',
  },
  {
    id: 8,
    title: 'Title 8',
    description: 'Description 8',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    price: 19,
    currency: '$',
  },
  {
    id: 9,
    title: 'Very Long Course Title as Example 9',
    description: 'Description 9',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    price: 25,
    currency: '$',
  },
];
